MONGODB_HOST: mongodb-{{ env }}.venkatesh.fun # mongodb-dev.venkatesh.fun
REDIS_HOST: redis-{{ env }}.venkatesh.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.venkatesh.fun
CART_HOST: cart.backend-alb-{{ env }}.venkatesh.fun
USER_HOST: user.backend-alb-{{ env }}.venkatesh.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.venkatesh.fun
MYSQL_HOST: mysql-{{ env }}.venkatesh.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.venkatesh.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.venkatesh.fun