MONGODB_HOST: mongodb-{{ env }}.venkatesh.fun # mongodb-dev.venkatesh.fun
REDIS_HOST: redis-{{ env }}.venkatesh.fun
CATALOGUE_HOST: catalogue-{{ env }}.venkatesh.fun
CART_HOST: cart-{{ env }}.venkatesh.fun
USER_HOST: user-{{ env }}.venkatesh.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.venkatesh.fun
MYSQL_HOST: mysql-{{ env }}.venkatesh.fun
SHIPPING_HOST: shipping-{{ env }}.venkatesh.fun
PAYMENT_HOST: payment-{{ env }}.venkatesh.fun